apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrate-{{ .Release.Revision }}"
  annotations: {"helm.sh/hook": pre-install\,pre-upgrade, "helm.sh/hook-delete-policy": before-hook-creation\,hook-succeeded}
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          command: [npx, prisma, migrate, deploy]
          envFrom: [{secretRef: {name: {{ .Values.secrets.externalSecretName }}}}]
