apiVersion: v1
kind: Service
metadata: {name: {{ .Release.Name }}-api}
spec: {selector: {app: {{ .Release.Name }}-api}, ports: [{name: http, port: 3000, targetPort: http}]}
---
apiVersion: v1
kind: Service
metadata: {name: {{ .Release.Name }}-web}
spec: {selector: {app: {{ .Release.Name }}-web}, ports: [{name: http, port: 8080, targetPort: http}]}
